services:
  # 1. PulsePoll Go Gin Backend (Web Service)
  - type: web
    name: pulsepoll-backend
    runtime: go
    plan: free
    rootDir: backend
    buildCommand: go build -o server ./cmd/server
    startCommand: ./server
    envVars:
      - key: PORT
        value: 8080
      - key: MONGO_URI
        value: mongodb+srv://Gowtham:sqMbDrg2ob5NLuV5@cluster0.hdxupyi.mongodb.net/?retryWrites=true&w=majority
      - key: MONGO_DB_NAME
        value: live_polling_db
      - key: REDIS_URI
        value: rediss://default:gQAAAAAABF8_AAIgcDFjYTQ0MDI2MjQxNTY0YTVlYTJiYTU3Y2QwZjJlYzhjMQ@enough-heron-286527.upstash.io:6379
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      - key: ENV
        value: production

  # 2. PulsePoll React Frontend (Static Web Service)
  - type: web
    name: pulsepoll-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://pulsepoll-backend-i4aq.onrender.com
      - key: VITE_WS_URL
        value: wss://pulsepoll-backend-i4aq.onrender.com
